--------------------------------------------------------
--  DDL for Table ERS_REIMBURSEMENT
--------------------------------------------------------

  CREATE TABLE "REIMBURSE"."ERS_REIMBURSEMENT" 
   (	"REIMB_ID" NUMBER(30,0), 
	"REIMB_AMOUNT" NUMBER(30,0), 
	"REIMB_SUBMITTED" TIMESTAMP (6), 
	"REIMB_RESOLVED" TIMESTAMP (6), 
	"REIMB_DESCRIPTION" VARCHAR2(250 BYTE), 
	"REIMB_RECIEPT" BLOB, 
	"REIMB_AUTHOR" NUMBER(30,0), 
	"REIMB_RESOLVER" NUMBER(30,0), 
	"REIMB_STATUS_ID" NUMBER(30,0), 
	"REIMB_TYPE_ID" NUMBER(30,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("REIMB_RECIEPT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index ERS_REIMBURSEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REIMBURSE"."ERS_REIMBURSEMENT_PK" ON "REIMBURSE"."ERS_REIMBURSEMENT" ("REIMB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ERS_REIMBURSEMENT
--------------------------------------------------------

  ALTER TABLE "REIMBURSE"."ERS_REIMBURSEMENT" ADD CONSTRAINT "ERS_REIMBURSEMENT_PK" PRIMARY KEY ("REIMB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REIMBURSE"."ERS_REIMBURSEMENT" MODIFY ("REIMB_ID" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Table ERS_USERS
--------------------------------------------------------

  CREATE TABLE "REIMBURSE"."ERS_USERS" 
   (	"ERS_USERS_ID" NUMBER(30,0), 
	"ERS_USERNAME" VARCHAR2(50 BYTE)UNIQUE, 
	"ERS_PASSWORD" VARCHAR2(50 BYTE), 
	"USER_FIRST_NAME" VARCHAR2(100 BYTE), 
	"USER_LAST_NAME" VARCHAR2(100 BYTE), 
	"USER_EMAIL" VARCHAR2(150 BYTE)UNIQUE, 
	"USER_ROLE_ID" NUMBER(30,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ERS_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REIMBURSE"."ERS_USERS_PK" ON "REIMBURSE"."ERS_USERS" ("ERS_USERS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ERS_USERS
--------------------------------------------------------

  ALTER TABLE "REIMBURSE"."ERS_USERS" ADD CONSTRAINT "ERS_USERS_PK" PRIMARY KEY ("ERS_USERS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REIMBURSE"."ERS_USERS" MODIFY ("ERS_USERS_ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  DDL for Table ERS_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "REIMBURSE"."ERS_USER_ROLES" 
   (	"ERS_USER_ROLE_ID" NUMBER(30,0), 
	"USER_ROLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ERS_USER_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REIMBURSE"."ERS_USER_ROLES_PK" ON "REIMBURSE"."ERS_USER_ROLES" ("ERS_USER_ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ERS_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "REIMBURSE"."ERS_USER_ROLES" ADD CONSTRAINT "ERS_USER_ROLES_PK" PRIMARY KEY ("ERS_USER_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REIMBURSE"."ERS_USER_ROLES" MODIFY ("ERS_USER_ROLE_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table ERS_REIMBURSEMENT_STATUS
--------------------------------------------------------

  CREATE TABLE "REIMBURSE"."ERS_REIMBURSEMENT_STATUS" 
   (	"REIMB_STATUS_ID" NUMBER(30,0), 
	"REIMB_STATUS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ERS_REIMBURSEMENT_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REIMBURSE"."ERS_REIMBURSEMENT_STATUS_PK" ON "REIMBURSE"."ERS_REIMBURSEMENT_STATUS" ("REIMB_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ERS_REIMBURSEMENT_STATUS
--------------------------------------------------------

  ALTER TABLE "REIMBURSE"."ERS_REIMBURSEMENT_STATUS" ADD CONSTRAINT "ERS_REIMBURSEMENT_STATUS_PK" PRIMARY KEY ("REIMB_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REIMBURSE"."ERS_REIMBURSEMENT_STATUS" MODIFY ("REIMB_STATUS_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table ERS_REIMBURSEMENT_TYPE
--------------------------------------------------------

  CREATE TABLE "REIMBURSE"."ERS_REIMBURSEMENT_TYPE" 
   (	"REIMB_TYPE_ID" NUMBER(30,0), 
	"REIMB_TYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ERS_REIMBURSEMENT_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REIMBURSE"."ERS_REIMBURSEMENT_TYPE_PK" ON "REIMBURSE"."ERS_REIMBURSEMENT_TYPE" ("REIMB_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ERS_REIMBURSEMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "REIMBURSE"."ERS_REIMBURSEMENT_TYPE" ADD CONSTRAINT "ERS_REIMBURSEMENT_TYPE_PK" PRIMARY KEY ("REIMB_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REIMBURSE"."ERS_REIMBURSEMENT_TYPE" MODIFY ("REIMB_TYPE_ID" NOT NULL ENABLE);

