CREATE TABLE Pet(
name VARCHAR2(50) PRIMARY KEY,
type VARCHAR2(50)
);

SELECT * FROM Pet;

-- auto increment
CREATE SEQUENCE key_increment
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trigger_for_key_increment
BEFORE INSERT
ON Pet
FOR EACH ROW
BEGIN
 IF(:new.ID IS NULL) THEN
 SELECT Pet.nextval
 INTO :new.ID
 FROM DUAL;
 END IF;
END;