package appModels;

public class Accounts {
	int AutoGeneratedNum;
	String Account_Name;
	String Username1;
	String Username2;
	String account_type;
	int balance;
	int account_State;
	
	
	
	
	//int autoGeneratedNum 
	public Accounts(int autoGeneratedNum, String account_Name, String username1, String username2, String account_type,
			int balance, int account_State) {
		super();
		AutoGeneratedNum = autoGeneratedNum;
		Account_Name = account_Name;
		Username1 = username1;
		Username2 = username2;
		this.account_type = account_type;
		this.balance = balance;
		this.account_State = account_State;
	}
	
	public Accounts( String account_Name, String username1, String username2, String account_type,
			int balance, int account_State) {
		super();
		//AutoGeneratedNum = autoGeneratedNum;
		Account_Name = account_Name;
		Username1 = username1;
		Username2 = username2;
		this.account_type = account_type;
		this.balance = balance;
		this.account_State = account_State;
	}





	public int getAutoGeneratedNum() {
		return AutoGeneratedNum;
	}



	public void setAutoGeneratedNum(int autoGeneratedNum) {
		AutoGeneratedNum = autoGeneratedNum;
	}





	public String getAccount_Name() {
		return Account_Name;
	}





	public void setAccount_Name(String account_Name) {
		Account_Name = account_Name;
	}





	public String getUsername1() {
		return Username1;
	}





	public void setUsername1(String username1) {
		Username1 = username1;
	}





	public String getUsername2() {
		return Username2;
	}





	public void setUsername2(String username2) {
		Username2 = username2;
	}





	public String getAccount_type() {
		return account_type;
	}





	public void setAccount_type(String account_type) {
		this.account_type = account_type;
	}





	public int getBalance() {
		return balance;
	}





	public void setBalance(int balance) {
		this.balance = balance;
	}





	public int getAccount_State() {
		return account_State;
	}





	public void setAccount_State(int account_State) {
		this.account_State = account_State;
	}




	// + AutoGeneratedNum

	@Override
	public String toString() {
		return "Accounts [AutoGeneratedNum=" + AutoGeneratedNum + ", Account_Name=" + Account_Name + ", Username1="
				+ Username1 + ", Username2=" + Username2 + ", account_type=" + account_type + ", balance=" + balance
				+ ", account_State=" + account_State + "]";
	}
		
	
}
