package com.homework.question4;

import java.util.Scanner; // import scanner class to take user input

public class Main {
	public static void main(String[] args)
	{
		// Q4. Write a program to compute N factorial
		
		boolean myBool = true; // use boolean for while loop
		
		Scanner myInput = new Scanner(System.in); // create an instance of the Scanner class
		System.out.print("Enter in a number: ");  
		int findFactorial = 0;
		
		// ask for user input loop until not true
		while(myBool)
		{
			findFactorial = myInput.nextInt(); 
			if(findFactorial < 0)
			{
				System.out.print("\nEnter a positive number: ");
			}
			else
			{
				break; 
			}
		}
		
		// call factorial function to compute value for N
		computerFactorial(findFactorial); 
	}

	// function template generated by Spring
	private static void computerFactorial(int f) {
		
		// condition if 0 is input
		if(f == 0)
		{
			System.out.println("Factorial of "+f+" is equal to: 1");
		}
		else
		{
			int temp = 1; // make temp 1 so not to multiply by zero
			
			for(int r = f; r >= 1; r--)
			{
				temp = temp * r; 
			}
			System.out.println("Factorial: "+temp);
			
		}
	}
}
